Improves the installation script

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,36 +1,52 @@
-#!/usr/bin/env sh
+#!/bin/bash
 
+DEPENDENCIES_OK=true
+declare -a MISSING
 echo -n "Checking dependencies..."
-command -v git   >/dev/null 2>&1 || { echo >&2 "git is not installed. Aborting.";   exit 1; }
-command -v zsh   >/dev/null 2>&1 || { echo >&2 "zsh is not installed. Aborting.";   exit 1; }
-command -v tmux  >/dev/null 2>&1 || { echo >&2 "tmux is not installed. Aborting.";  exit 1; }
-command -v vim   >/dev/null 2>&1 || { echo >&2 "vim is not installed. Aborting.";   exit 1; }
-command -v ctags >/dev/null 2>&1 || { echo >&2 "ctags is not installed. Aborting."; exit 1; }
-echo "passed.\n"
+command -v git   >/dev/null 2>&1 \
+    || DEPENDENCIES_OK=false MISSING=("${MISSING[@]}" "git")
+command -v zsh   >/dev/null 2>&1 \
+    || DEPENDENCIES_OK=false MISSING=("${MISSING[@]}" "zsh")
+command -v tmux  >/dev/null 2>&1 \
+    || DEPENDENCIES_OK=false MISSING=("${MISSING[@]}" "tmux")
+command -v vim   >/dev/null 2>&1 \
+    || DEPENDENCIES_OK=false MISSING=("${MISSING[@]}" "vim")
+command -v ctags >/dev/null 2>&1 \
+    || DEPENDENCIES_OK=false MISSING=("${MISSING[@]}" "ctags")
 
+if [[ "$DEPENDENCIES_OK" == "true" ]]; then
+    echo "passed."
+else
+    echo "failed!"
+    echo "Missing dependencies: ${MISSING[@]}"
+    exit 1
+fi
+
+BACKUP_FOLDER=$HOME/.myutilitybelt/install-backup/$(date +%Y%m%d%H%M%S)
+mkdir -p $BACKUP_FOLDER
 echo -n "Backing up previous configuration files..."
-[ -h ~/.bashrc ]        && mv ~/.bashrc ~/.bashrc-bkp
-[ -h ~/.bash_aliases ]  && mv ~/.bash_aliases ~/.bash_aliases-bkp
-[ -h ~/.zshrc ]         && mv ~/.zshrc ~/.zshrc-bkp
-[ -h ~/.vim ]           && mv ~/.vim ~/.vim-bkp
-[ -h ~/.vimrc ]         && mv ~/.vimrc ~/.vimrc-bkp
-[ -h ~/.tmux.conf ]     && mv ~/.tmux.conf ~/.tmux.conf-bkp
-[ -h ~/.gitconfig ]     && mv ~/.gitconfig ~/.gitconfig-bkp
-echo "done.\n"
+mv $HOME/.bashrc       $BACKUP_FOLDER || true
+mv $HOME/.bash_aliases $BACKUP_FOLDER || true
+mv $HOME/.zshrc        $BACKUP_FOLDER || true
+mv $HOME/.vim          $BACKUP_FOLDER || true
+mv $HOME/.vimrc        $BACKUP_FOLDER || true
+mv $HOME/.tmux.conf    $BACKUP_FOLDER || true
+mv $HOME/.gitconfig    $BACKUP_FOLDER || true
+echo "done."
 
 echo -n "Creating the symlinks..."
-ln -s ~/.myutilitybelt/bash/bashrc ~/.bashrc
-ln -s ~/.myutilitybelt/bash/bash_aliases ~/.bash_aliases
-ln -s ~/.myutilitybelt/zsh/zshrc ~/.zshrc
-ln -s ~/.myutilitybelt/vim ~/.vim
-ln -s ~/.myutilitybelt/vim/vimrc ~/.vimrc
-ln -s ~/.myutilitybelt/tmux/tmux.conf ~/.tmux.conf
-ln -s ~/.myutilitybelt/git/gitconfig ~/.gitconfig
-echo "done.\n"
+ln -s $HOME/.myutilitybelt/bash/bashrc       $HOME/.bashrc
+ln -s $HOME/.myutilitybelt/bash/bash_aliases $HOME/.bash_aliases
+ln -s $HOME/.myutilitybelt/zsh/zshrc         $HOME/.zshrc
+ln -s $HOME/.myutilitybelt/vim               $HOME/.vim
+ln -s $HOME/.myutilitybelt/vim/vimrc         $HOME/.vimrc
+ln -s $HOME/.myutilitybelt/tmux/tmux.conf    $HOME/.tmux.conf
+ln -s $HOME/.myutilitybelt/git/gitconfig     $HOME/.gitconfig
+echo "done."
 
 echo -n "Installing Vim plugins..."
-vim -N -u ~/.myutilitybelt/vim/vundle.vim -c ':BundleCleanInstallQuit'
-echo "done.\n"
+vim -N -u $HOME/.myutilitybelt/vim/vundle.vim -c ':BundleCleanInstallQuit'
+echo "done."
 
 echo "--- Installation of myutilitybelt complete ---"
 exit 0
